/* global google */

import { importLibrary, setOptions } from "@googlemaps/js-api-loader";
import { createFileRoute } from "@tanstack/react-router";
import * as React from "react";

type DomainVertex = { idx: number; lat: number; lng: number };

async function fetchDomain(): Promise<{ vertices: DomainVertex[] }> {
  const res = await fetch("/api/domain");
  if (!res.ok) throw new Error("載入領域失敗");
  return res.json() as Promise<{ vertices: DomainVertex[] }>;
}

// @ts-expect-error Router types are generated by @tanstack/router-plugin
export const Route = createFileRoute("/")({
  component: DomainPage,
});

function DomainPage() {
  const [vertices, setVertices] = React.useState<DomainVertex[]>([]);
  const [secret, setSecret] = React.useState("");

  const mapDivRef = React.useRef<HTMLDivElement | null>(null);
  const searchBoxRef = React.useRef<HTMLDivElement | null>(null);
  const mapRef = React.useRef<google.maps.Map | null>(null);
  const polygonRef = React.useRef<google.maps.Polygon | null>(null);
  const markerRef =
    React.useRef<google.maps.marker.AdvancedMarkerElement | null>(null);
  const [mapsReady, setMapsReady] = React.useState(false);
  const [placeResult, setPlaceResult] = React.useState<{
    name: string;
    lat: number;
    lng: number;
    inside: boolean;
  } | null>(null);

  const googleMapsApiKey = import.meta.env.VITE_GOOGLE_MAPS_API_KEY as
    | string
    | undefined;

  React.useEffect(() => {
    void fetchDomain()
      .then((data) => setVertices(data.vertices))
      .catch(() => {
        // Surface error via existing UI patterns (kept minimal).
        setVertices([]);
      });
  }, []);

  React.useEffect(() => {
    let cancelled = false;

    async function init() {
      if (!googleMapsApiKey) return;
      if (!mapDivRef.current) return;

      setOptions({
        key: googleMapsApiKey,
        v: "weekly",
      });

      // Bootstraps the Maps JS script; after this, use google.maps.importLibrary
      // (matches Google Maps Platform examples for Places UI elements).
      await importLibrary("maps");
      await window.google.maps.importLibrary("places");
      if (cancelled) return;

      const center = vertices[0]
        ? { lat: vertices[0].lat, lng: vertices[0].lng }
        : { lat: 0, lng: 0 };

      const map = new window.google.maps.Map(mapDivRef.current, {
        center,
        zoom: 14,
        mapTypeControl: false,
        streetViewControl: false,
        fullscreenControl: false,
        mapId: import.meta.env.VITE_GOOGLE_MAPS_ID,
      });

      mapRef.current = map;
      setMapsReady(true);
    }

    void init();

    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [googleMapsApiKey]);

  React.useEffect(() => {
    if (!mapsReady) return;
    if (!mapRef.current) return;

    const path = vertices
      .slice()
      .sort((a, b) => a.idx - b.idx)
      .map((v) => ({ lat: v.lat, lng: v.lng }));

    polygonRef.current?.setMap(null);
    polygonRef.current = new window.google.maps.Polygon({
      paths: path,
      strokeColor: "#00b8d4",
      strokeOpacity: 0.95,
      strokeWeight: 2.5,
      fillColor: "#00e5ff",
      fillOpacity: 0.28,
      clickable: false,
    });
    polygonRef.current.setMap(mapRef.current);

    if (path[0]) {
      mapRef.current.panTo(path[0]);
    }

    return () => {
      polygonRef.current?.setMap(null);
      polygonRef.current = null;
    };
  }, [mapsReady, vertices]);

  React.useEffect(() => {
    if (!mapsReady) return;
    if (!mapRef.current) return;
    if (!searchBoxRef.current) return;

    let cancelled = false;
    let el: HTMLElement | null = null;

    const onPlaceSelect = async (event: Event) => {
      try {
        // Google example shape:
        // placeAutocomplete.addEventListener('gmp-select', async ({ placePrediction }) => { ... })
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const { placePrediction } = event as any;
        if (!placePrediction) return;

        const place = (
          placePrediction as google.maps.places.PlacePrediction
        ).toPlace();
        await place.fetchFields({ fields: ["displayName", "location"] });

        const loc = place.location;
        const polygon = polygonRef.current;
        if (!loc || !polygon) return;

        const lat = loc.lat();
        const lng = loc.lng();

        await Promise.all([
          window.google.maps.importLibrary("geometry"),
          window.google.maps.importLibrary("marker"),
        ]);

        const inside = window.google.maps.geometry.poly.containsLocation(
          loc,
          polygon,
        );

        if (markerRef.current) {
          markerRef.current.map = null;
        }
        markerRef.current = new window.google.maps.marker.AdvancedMarkerElement(
          {
            map: mapRef.current!,
            position: { lat, lng },
            title: place.displayName ?? "結果",
          },
        );

        mapRef.current!.panTo({ lat, lng });

        setPlaceResult({
          name: place.displayName ?? "結果",
          lat,
          lng,
          inside,
        });
      } catch (err) {
        console.error("Place selection failed", err);
      }
    };

    void (async () => {
      // Ensure Places UI is ready before creating PlaceAutocompleteElement.
      await window.google.maps.importLibrary("places");
      if (cancelled) return;
      if (!searchBoxRef.current) return;

      // New Places UI (recommended): PlaceAutocompleteElement
      el = new window.google.maps.places.PlaceAutocompleteElement(
        {},
      ) as unknown as HTMLElement;
      (el as unknown as { placeholder: string }).placeholder = "搜尋地點…";
      (el as HTMLElement).style.width = "100%";
      (el as HTMLElement).style.maxWidth = "100%";
      (el as HTMLElement).style.boxSizing = "border-box";

      // Ensure container is empty before mounting
      searchBoxRef.current.replaceChildren(el);

      el.addEventListener("gmp-select", onPlaceSelect);
    })();

    return () => {
      cancelled = true;
      el?.removeEventListener("gmp-select", onPlaceSelect);
      if (markerRef.current) {
        markerRef.current.map = null;
      }
      markerRef.current = null;
    };
  }, [mapsReady]);

  async function saveVertex(idx: number, lat: number, lng: number) {
    const res = await fetch(`/api/domain/vertex/${idx}`, {
      method: "PUT",
      headers: {
        "content-type": "application/json",
        "x-domain-secret": secret,
      },
      body: JSON.stringify({ lat, lng }),
    });

    if (!res.ok) {
      const text = await res.text().catch(() => "");
      throw new Error(text || "儲存座標失敗");
    }
    const data = (await res.json()) as { vertices: DomainVertex[] };
    setVertices(data.vertices);
  }

  return (
    <main className="page-wrap md:px-4 pb-10 pt-10">
      <section className="island-shell rounded-[2rem] p-6 sm:p-8">
        <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <h1 className="display-title m-0 text-3xl font-bold text-[var(--sea-ink)] sm:text-4xl">
              領域展開
            </h1>
            <p className="mt-2 max-w-2xl text-sm leading-7 text-[var(--sea-ink-soft)] sm:text-base">
              我們都會想要知道現在的位置是否在領域內。
            </p>
          </div>
        </div>

        <div className="mt-6 grid gap-5 lg:grid-cols-[minmax(0,1.4fr)_minmax(0,1fr)]">
          <div className="min-w-0 space-y-3">
            <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
              <div className="w-full">
                <label className="text-xs font-semibold tracking-wide text-[var(--sea-ink-soft)]">
                  地點搜尋
                </label>
                <div
                  ref={searchBoxRef}
                  className="mt-1 w-full rounded-xl border border-[var(--line)] bg-[var(--surface-strong)] px-3 py-2 text-sm text-[var(--sea-ink)] shadow-[0_10px_30px_rgba(23,58,64,0.06)] outline-none focus-within:border-[rgba(50,143,151,0.55)]"
                />
              </div>
            </div>

            {placeResult ? (
              <div className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-4 text-sm">
                <div className="flex flex-wrap items-center justify-between gap-3">
                  <div className="min-w-0">
                    <div className="font-semibold text-[var(--sea-ink)]">
                      {placeResult.name}
                    </div>
                    <div className="text-[var(--sea-ink-soft)]">
                      {placeResult.lat.toFixed(6)}, {placeResult.lng.toFixed(6)}
                    </div>
                  </div>
                  <div
                    className={`rounded-full px-3 py-1 text-xs font-semibold ${
                      placeResult.inside
                        ? "bg-[rgba(47,106,74,0.14)] text-[var(--palm)]"
                        : "bg-[rgba(23,58,64,0.08)] text-[var(--sea-ink-soft)]"
                    }`}
                  >
                    {placeResult.inside ? "在領域內QQ" : "不在領域內，恭喜！"}
                  </div>
                </div>
              </div>
            ) : (
              <div className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-4 text-sm text-[var(--sea-ink-soft)]">
                選擇搜尋結果後，會顯示是否位於領域內。
              </div>
            )}

            <div
              ref={mapDivRef}
              className="h-[460px] w-full overflow-hidden rounded-2xl border border-[var(--line)] bg-[color-mix(in_oklab,var(--foam)_80%,white)] shadow-[0_18px_40px_rgba(23,58,64,0.08)]"
            />

            {!googleMapsApiKey ? (
              <div className="rounded-2xl border border-[var(--line)] bg-[rgba(255,255,255,0.55)] p-4 text-sm text-[var(--sea-ink-soft)]">
                缺少 <code>VITE_GOOGLE_MAPS_API_KEY</code>。請加入{" "}
                <code>.env</code> 並重新啟動開發伺服器。
              </div>
            ) : null}
          </div>

          <aside className="min-w-0 space-y-3">
            <div className="flex w-full flex-col gap-2 sm:w-[360px]">
              <label className="text-xs font-semibold tracking-wide text-[var(--sea-ink-soft)]">
                Update Secret（header <code>x-domain-secret</code>）
              </label>
              <input
                value={secret}
                onChange={(e) => setSecret(e.target.value)}
                placeholder="DOMAIN_SECRET"
                className="w-full rounded-xl border border-[var(--line)] bg-[var(--surface-strong)] px-3 py-2 text-sm text-[var(--sea-ink)] shadow-[0_10px_30px_rgba(23,58,64,0.06)] outline-none focus:border-[rgba(50,143,151,0.55)]"
              />
            </div>
            <div className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-5">
              <div className="text-sm font-semibold text-[var(--sea-ink)]">
                頂點（idx 0–3）
              </div>
              <p className="mt-1 text-sm leading-6 text-[var(--sea-ink-soft)]">
                編輯 lat/lng 後點擊儲存，即可更新單一頂點座標。
              </p>
            </div>

            <VertexEditor
              vertices={vertices}
              onSave={(idx, lat, lng) => saveVertex(idx, lat, lng)}
            />
          </aside>
        </div>
      </section>
    </main>
  );
}

function VertexEditor(props: {
  vertices: DomainVertex[];
  onSave: (idx: number, lat: number, lng: number) => Promise<void>;
}) {
  const ordered = props.vertices.slice().sort((a, b) => a.idx - b.idx);
  const [drafts, setDrafts] = React.useState(() =>
    ordered.map((v) => ({
      idx: v.idx,
      lat: String(v.lat),
      lng: String(v.lng),
    })),
  );
  const [busyIdx, setBusyIdx] = React.useState<number | null>(null);
  const [error, setError] = React.useState<string | null>(null);

  React.useEffect(() => {
    setDrafts(
      ordered.map((v) => ({
        idx: v.idx,
        lat: String(v.lat),
        lng: String(v.lng),
      })),
    );
  }, [props.vertices]);

  return (
    <div className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-5">
      {error ? (
        <div className="mb-3 rounded-xl border border-[rgba(23,58,64,0.14)] bg-[rgba(255,255,255,0.55)] px-3 py-2 text-sm text-[var(--sea-ink-soft)]">
          {error}
        </div>
      ) : null}

      <div className="space-y-3">
        {drafts.map((d) => (
          <div
            key={d.idx}
            className="rounded-2xl border border-[rgba(23,58,64,0.12)] bg-white/50 p-3"
          >
            <div className="flex items-center justify-between gap-3">
              <div className="text-sm font-semibold text-[var(--sea-ink)]">
                頂點 {d.idx}
              </div>
              <button
                type="button"
                disabled={busyIdx === d.idx}
                onClick={() => {
                  setError(null);
                  const lat = Number(d.lat);
                  const lng = Number(d.lng);
                  if (!Number.isFinite(lat) || !Number.isFinite(lng)) {
                    setError("經緯度必須是數字。");
                    return;
                  }
                  setBusyIdx(d.idx);
                  props
                    .onSave(d.idx, lat, lng)
                    .catch((e: unknown) => {
                      setError(e instanceof Error ? e.message : "儲存座標失敗");
                    })
                    .finally(() => setBusyIdx(null));
                }}
                className="rounded-xl border border-[rgba(50,143,151,0.25)] bg-[rgba(79,184,178,0.14)] px-3 py-1.5 text-xs font-semibold text-[var(--lagoon-deep)] transition hover:-translate-y-0.5 hover:bg-[rgba(79,184,178,0.22)] disabled:opacity-60 disabled:hover:translate-y-0"
              >
                {busyIdx === d.idx ? "儲存中…" : "儲存"}
              </button>
            </div>

            <div className="mt-3 grid gap-2 sm:grid-cols-2">
              <label className="text-xs font-semibold tracking-wide text-[var(--sea-ink-soft)]">
                Lat
                <input
                  value={d.lat}
                  onChange={(e) =>
                    setDrafts((prev) =>
                      prev.map((p) =>
                        p.idx === d.idx ? { ...p, lat: e.target.value } : p,
                      ),
                    )
                  }
                  className="mt-1 w-full rounded-xl border border-[var(--line)] bg-[var(--surface-strong)] px-3 py-2 text-sm text-[var(--sea-ink)] outline-none focus:border-[rgba(50,143,151,0.55)]"
                />
              </label>
              <label className="text-xs font-semibold tracking-wide text-[var(--sea-ink-soft)]">
                Lng
                <input
                  value={d.lng}
                  onChange={(e) =>
                    setDrafts((prev) =>
                      prev.map((p) =>
                        p.idx === d.idx ? { ...p, lng: e.target.value } : p,
                      ),
                    )
                  }
                  className="mt-1 w-full rounded-xl border border-[var(--line)] bg-[var(--surface-strong)] px-3 py-2 text-sm text-[var(--sea-ink)] outline-none focus:border-[rgba(50,143,151,0.55)]"
                />
              </label>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
