/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDomainRouteImport } from './routes/api/domain'
import { Route as ApiDomainVertexIdxRouteImport } from './routes/api/domain/vertex/$idx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDomainRoute = ApiDomainRouteImport.update({
  id: '/api/domain',
  path: '/api/domain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDomainVertexIdxRoute = ApiDomainVertexIdxRouteImport.update({
  id: '/vertex/$idx',
  path: '/vertex/$idx',
  getParentRoute: () => ApiDomainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/domain': typeof ApiDomainRouteWithChildren
  '/api/domain/vertex/$idx': typeof ApiDomainVertexIdxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/domain': typeof ApiDomainRouteWithChildren
  '/api/domain/vertex/$idx': typeof ApiDomainVertexIdxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/domain': typeof ApiDomainRouteWithChildren
  '/api/domain/vertex/$idx': typeof ApiDomainVertexIdxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/domain' | '/api/domain/vertex/$idx'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/domain' | '/api/domain/vertex/$idx'
  id: '__root__' | '/' | '/api/domain' | '/api/domain/vertex/$idx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDomainRoute: typeof ApiDomainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/domain': {
      id: '/api/domain'
      path: '/api/domain'
      fullPath: '/api/domain'
      preLoaderRoute: typeof ApiDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/domain/vertex/$idx': {
      id: '/api/domain/vertex/$idx'
      path: '/vertex/$idx'
      fullPath: '/api/domain/vertex/$idx'
      preLoaderRoute: typeof ApiDomainVertexIdxRouteImport
      parentRoute: typeof ApiDomainRoute
    }
  }
}

interface ApiDomainRouteChildren {
  ApiDomainVertexIdxRoute: typeof ApiDomainVertexIdxRoute
}

const ApiDomainRouteChildren: ApiDomainRouteChildren = {
  ApiDomainVertexIdxRoute: ApiDomainVertexIdxRoute,
}

const ApiDomainRouteWithChildren = ApiDomainRoute._addFileChildren(
  ApiDomainRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDomainRoute: ApiDomainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
